# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: vimdoc
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
    - GH_REPO_REF: github.com/yegappan/vimdoc.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - touch /tmp/build

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/doc
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
